POST http://localhost:8081/inputs/post
Content-Type: application/json

{
  "userInput": "arcana"
}

###
POST http://localhost:8081/inputs?post=arcana
Content-Type: application/json

###
GET http://localhost:8081/inputs?post=arcana
Content-Type: application/json


